# Generated by Django 3.0.4 on 2020-03-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200322_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='questions',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='seconds',
            field=models.IntegerField(default=120),
        ),
    ]
