# Generated by Django 3.0.4 on 2020-03-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200322_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='short_sound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='startbtn',
            field=models.BooleanField(default=False),
        ),
    ]
