# Generated by Django 3.0.4 on 2020-03-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200322_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='voice',
            field=models.BooleanField(default=True),
        ),
    ]
