# Generated by Django 3.0.4 on 2020-04-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='forbidden',
            field=models.BooleanField(default=True),
        ),
    ]
